SKILL_MAP: dict[str, str] = {
    "python": "python",
    "django": "django",
    "flask": "flask",
    "fastapi": "fastapi",
    "javascript": "javascript",
    "typescript": "typescript",
    "react": "react-js",
    "nextjs": "next-js",
    "next": "next-js",
    "vue": "vue-js",
    "angular": "angular-js",
    "node": "nodejs",
    "nodejs": "nodejs",
    "php": "php",
    "laravel": "laravel",
    "wordpress": "wordpress",
    "java": "java",
    "spring": "spring-framework",
    "kotlin": "kotlin",
    "android": "android",
    "swift": "swift",
    "ios": "ios-development",
    "flutter": "flutter",
    "dart": "flutter",
    "react native": "react-native",
    "c#": "c-sharp-programming",
    "dotnet": "net-framework",
    ".net": "net-framework",
    "c++": "c-plus-plus-programming",
    "golang": "golang",
    "go": "golang",
    "rust": "rust",
    "ruby": "ruby-on-rails",
    "rails": "ruby-on-rails",
    "mysql": "mysql",
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "mongodb": "mongodb",
    "aws": "amazon-web-services",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "devops": "devops",
    "machine learning": "machine-learning",
    "ml": "machine-learning",
    "deep learning": "deep-learning",
    "data science": "data-science",
    "ai": "artificial-intelligence",
    "nlp": "natural-language-processing",
    "opencv": "opencv",
    "tensorflow": "tensorflow",
    "pytorch": "pytorch",
    "scraping": "web-scraping",
    "selenium": "selenium-webdriver",
    "automation": "robotic-process-automation",
    "excel": "microsoft-excel",
    "vba": "visual-basic",
    "figma": "figma",
    "graphic design": "graphic-design",
    "photoshop": "photoshop",
    "illustrator": "adobe-illustrator",
    "ui": "ui-design",
    "ux": "ux-design",
    "blockchain": "blockchain",
    "solidity": "solidity",
    "web3": "ethereum",
    "linux": "linux",
    "bash": "bash-scripting",
    "shopify": "shopify",
    "magento": "magento",
    "woocommerce": "woocommerce",
    # CAD / مکانیک / مهندسی
    "solidworks": "solidworks",
    "autocad": "autocad",
    "cad": "autocad",
    "catia": "catia",
    "ansys": "ansys",
    "fusion 360": "fusion-360",
    "fusion360": "fusion-360",
    "inventor": "autodesk-inventor",
    "revit": "autodesk-revit",
    "3dsmax": "3ds-max",
    "3ds max": "3ds-max",
    "maya": "autodesk-maya",
    "blender": "blender-3d",
    "cfd": "computational-fluid-dynamics",
    "fem": "finite-element-analysis",
    "matlab": "matlab",
    "simulink": "simulink",
    "mechanical engineering": "mechanical-engineering",
    "civil engineering": "civil-engineering",
    "electrical engineering": "electrical-engineering",
    "pcb": "pcb-design",
    "eagle": "eagle-pcb",
    "altium": "altium-designer",
    "arduino": "arduino",
    "raspberry": "raspberry-pi",
    "embedded": "embedded-systems",
    "fpga": "fpga",
    "plc": "plc-scada",
    "scada": "plc-scada",
}


def resolve_slug(skill: str) -> str:
    """Convert a user-provided skill name to a Freelancer.com URL slug."""
    key = skill.strip().lower()
    return SKILL_MAP.get(key, key.replace(" ", "-"))
